paulscherrerinstitute/scicat-ci

helm/configs/frontend/development/config.json
helm/configs/frontend/production/config.json
helm/configs/frontend/qa/config.json

Make CSCS retrieve more descriptive

---

helm/configs/backend/values.yaml

This reverts commit 22ba41db0dc1b2fb635df6952a61e58b99049ef8.

Revert "Double proxy buffer size"

---

proposals/src/proposals.py
proposals/src/tests/test_proposals.py
proposals/src/tests/test_utils.py
proposals/src/utils.py

https://tree.taiga.io/project/stephanegli-scicat/us/547?kanban-status=2540226&kanban-swimlane=2367

Set GET retry to 5 times with linear delay of 10s

---

helm/configs/backend/qa/values.yaml

Update with new QA functionalAccount secret

Trigger QA redeploy

---

.github/workflows/reusable.environment.yml
.github/workflows/scicat-be.yml

Reverts paulscherrerinstitute/scicat-ci#245

Revert "Add option to choose deployment env on dispatch"

---

.github/workflows/reusable.changes.yml

Fixes [CVE-2025-30066](https://www.cve.org/CVERecord?id=CVE-2025-30066)

deps: bump tj-actions/changed-files to v46

---

helm/configs/frontend/production/config.json

Reverts paulscherrerinstitute/scicat-ci#256

Revert "Disable temporarly URL retrieve"

---

proposals/docker-compose.dev.yml
proposals/src/main.py
proposals/src/tests/test_main.py

This is the lightest refactor I could do to add tests. Some other PRs will do a heavier refactor, now that tests are in place and set type

Extract formatting functions and add tests

---

proposals/src/main.py
proposals/src/scicat.py
proposals/src/tests/test_main.py
proposals/src/tests/test_scicat.py

Add scicat proposals class and move logic from main to dedicated classes

Scicat proposals class

---

proposals/src/tests/fixtures/mocked_data.py
proposals/src/tests/test_main.py
proposals/src/tests/test_scicat.py

Add fixtures for shared mocks

---

proposals/src/main.py
proposals/src/scicat.py
proposals/src/tests/fixtures/mocked_data.py
proposals/src/tests/test_main.py
proposals/src/tests/test_scicat.py

Move apis to scicat

---

proposals/src/orchestrator.py
proposals/src/proposals.py
proposals/src/scicat.py
proposals/src/tests/test_orchestrator.py
proposals/src/tests/test_proposals.py
proposals/src/tests/test_scicat.py

Delegate env fetching to classes

---

proposals/src/tests/test_main.py
proposals/src/tests/test_orchestrator.py
proposals/src/tests/test_proposals.py
proposals/src/tests/test_scicat.py

Use autospec to spot errors in mocks use

---

helm/configs/oaipmh/development/values.yaml

Demo results can be found [here](https://oaipmh.development.psi.ch/oaipmh/oai?verb=ListIdentifiers&metadataPrefix=oai_dc)

Connect OAIPMH to v4 in DEV

---

helm/configs/globus-proxy/development/config.yaml

Update globus endpoints for the globux-proxy.
Endpoint IDs changed as part of the recent permissions update.

Update available globus endpoints

---

helm/configs/scicat-exporter/development/values.yaml
helm/configs/scicat-exporter/values.yaml

needs https://github.com/paulscherrerinstitute/scicat-rocrate/pull/46 to be released first

don't preprend the token with "Bearer "

---

helm/configs/scicat-exporter/values.yaml

Adds support for zipped crates

bump `scicat-rocrate` version to 1.1.0

---

dev/config/frontend/config.json

Update dci-l ingestor URL

---

.github/workflows/scicat-fe-next.yml
helm/configs/frontend-next/qa/config.json
helm/configs/frontend-next/qa/values.yaml

Deploy fe_next to qa

---

helm/configs/oaipmh/qa/values.yaml

depends on https://github.com/paulscherrerinstitute/scicat-ci/pull/351

Connect oaipmh to be_next in qa

---

.github/workflows/proposals-sync.yml
helm/configs/proposals/qa/values.yaml

depends on https://github.com/paulscherrerinstitute/scicat-ci/pull/351

Connect qa proposals to be_next
